variables:
  CI_IMAGE_REPO: 'ci/${CI_PROJECT_NAME}'
  CI_IMAGE: 'registry.ddbuild.io/${CI_IMAGE_REPO}:v91906098-063416a9@sha256:1d045c48194af52d6765ff1c9fa12103b072ceb97c167522bd9b90ceb87673b2' # https://gitlab.ddbuild.io/DataDog/electron-sdk/-/jobs/1365640927

stages:
  - docker
  - test

default:
  tags: ['arch:amd64']
  image: $CI_IMAGE

build-container-image:
  stage: docker
  image: 'registry.ddbuild.io/images/docker:27.3.1'
  when: manual
  script: |-
    docker buildx build \
      --platform=linux/amd64 \
      --label target=build \
      --tag registry.ddbuild.io/${CI_IMAGE_REPO}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA} \
      --push \
      .

format:
  stage: test
  script:
    - yarn
    - yarn format:check

lint:
  stage: test
  script:
    - yarn
    - yarn lint

build:
  stage: test
  script:
    - yarn
    - yarn build

unit:
  stage: test
  script:
    - yarn
    - yarn test:unit

check-licenses:
  stage: test
  script:
    - yarn
    - node scripts/check-licenses.ts

e2e:
  stage: test
  script:
    - yarn
    - yarn test:e2e:ci
  artifacts:
    when: on_failure
    paths:
      - e2e/test-results/
      - e2e/playwright-report/
