variables:
  CI_IMAGE_REPO: 'ci/${CI_PROJECT_NAME}'
  CI_IMAGE: 'registry.ddbuild.io/${CI_IMAGE_REPO}:v91688719-11de542a@sha256:74eed547ec073d74b011ecaa861abdd3e0e7e81d49117cca509b756efbb8b2d3' # https://gitlab.ddbuild.io/DataDog/electron-sdk/-/jobs/1362784617

stages:
  - docker
  - test

default:
  tags: ['arch:amd64']
  image: $CI_IMAGE

build-container-image:
  stage: docker
  image: 'registry.ddbuild.io/images/docker:27.3.1'
  when: manual
  script: |-
    docker buildx build \
      --platform=linux/amd64 \
      --label target=build \
      --tag registry.ddbuild.io/${CI_IMAGE_REPO}:v${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA} \
      --push \
      .

format:
  stage: test
  script:
    - yarn
    - yarn format:check

lint:
  stage: test
  script:
    - yarn
    - yarn lint

build:
  stage: test
  script:
    - yarn
    - yarn build

unit:
  stage: test
  script:
    - yarn
    - yarn test:unit

check-licenses:
  stage: test
  script:
    - yarn
    - node scripts/check-licenses.ts

e2e:
  stage: test
  script:
    - yarn
    - yarn test:e2e:ci
  artifacts:
    when: on_failure
    paths:
      - e2e/test-results/
      - e2e/playwright-report/
