import * as fs from 'node:fs';
import * as path from 'node:path';
import { execSync } from 'node:child_process';
import { formatSize, printLog, runMain } from './lib/executionUtils.ts';

const ROOT_DIR = path.resolve(import.meta.dirname, '..');
const CRATE_DIR = path.join(ROOT_DIR, 'minidump-processor');
const PKG_DIR = path.join(CRATE_DIR, 'pkg');
const WASM_PATH = path.join(PKG_DIR, 'minidump_bg.wasm');
const MINIDUMP_JS_PATH = path.join(PKG_DIR, 'minidump.js');

runMain(() => {
  printLog('Building minidump-processor WASM...');

  execSync('wasm-pack build . --target nodejs --release --out-name minidump', {
    cwd: CRATE_DIR,
    stdio: 'inherit',
  });

  // Remove files generated by wasm-pack that we don't need:
  // - .gitignore: wasm-pack adds "*" to prevent committing pkg/, but we commit it intentionally
  // - package.json / README.md: npm publishing artifacts, not needed (we import the path directly)
  for (const file of ['.gitignore', 'package.json', 'README.md']) {
    fs.rmSync(path.join(PKG_DIR, file), { force: true });
  }

  printLog('Embedding WASM binary as base64...');

  const wasmBytes = fs.readFileSync(WASM_PATH);
  const base64 = wasmBytes.toString('base64');

  printLog(`  WASM size: ${formatSize(wasmBytes.length)} → base64: ${formatSize(base64.length)}`);

  // Replace the readFileSync loader in minidump.js with an inline base64 decode.
  // This makes the built SDK self-contained: no .wasm file needs to be distributed.
  const minidumpJs = fs.readFileSync(MINIDUMP_JS_PATH, 'utf-8');
  const patchedJs = minidumpJs.replace(
    /const wasmPath = `\$\{__dirname\}\/minidump_bg\.wasm`;\nconst wasmBytes = require\('fs'\)\.readFileSync\(wasmPath\);/,
    `const wasmBytes = Buffer.from('${base64}', 'base64');`
  );

  if (patchedJs === minidumpJs) {
    throw new Error('Failed to patch minidump.js: readFileSync loader block not found');
  }

  fs.writeFileSync(MINIDUMP_JS_PATH, patchedJs, 'utf-8');

  printLog(`Build complete. Artifacts in minidump-processor/pkg/`);
});
