import * as fs from 'node:fs';
import * as path from 'node:path';
import { execSync } from 'node:child_process';
import { formatSize, printLog, runMain } from './lib/executionUtils.ts';

const ROOT_DIR = path.resolve(import.meta.dirname, '..');
const CRATE_DIR = path.join(ROOT_DIR, 'minidump-processor');
const PKG_DIR = path.join(CRATE_DIR, 'pkg');
const WASM_PATH = path.join(PKG_DIR, 'minidump_bg.wasm');
const BASE64_JS_PATH = path.join(PKG_DIR, 'minidump_bg.wasm.base64.js');
const BASE64_DTS_PATH = path.join(PKG_DIR, 'minidump_bg.wasm.base64.d.ts');

runMain(() => {
  printLog('Building minidump-processor WASM...');

  execSync('wasm-pack build . --target web --release --out-name minidump', {
    cwd: CRATE_DIR,
    stdio: 'inherit',
  });

  // Remove files generated by wasm-pack that we don't need:
  // - .gitignore: wasm-pack adds "*" to prevent committing pkg/, but we commit it intentionally
  // - package.json / README.md: npm publishing artifacts, not needed (we import the path directly)
  for (const file of ['.gitignore', 'package.json', 'README.md']) {
    fs.rmSync(path.join(PKG_DIR, file), { force: true });
  }

  printLog('Embedding WASM binary as base64...');

  const wasmBytes = fs.readFileSync(WASM_PATH);
  const base64 = wasmBytes.toString('base64');

  printLog(`  WASM size: ${formatSize(wasmBytes.length)} → base64: ${formatSize(base64.length)}`);

  // Export WASM binary as a base64 JS module.
  // This makes the built SDK self-contained: no .wasm file needs to be distributed.
  // The wrapper in src/wasm/index.ts uses init(buffer) to load it at runtime.
  fs.writeFileSync(BASE64_JS_PATH, `export const WASM_BASE64 = '${base64}';\n`);
  fs.writeFileSync(BASE64_DTS_PATH, `export declare const WASM_BASE64: string;\n`);

  // Remove the .wasm file — it's now embedded in the base64 module
  fs.rmSync(WASM_PATH);

  printLog(`Build complete. Artifacts in minidump-processor/pkg/`);
});
