import { compile } from 'json-schema-to-typescript';
import { execSync } from 'node:child_process';
import * as fs from 'node:fs';
import * as path from 'node:path';
import { printLog } from './lib/executionUtils.ts';

interface SchemaConfig {
  schemaPath: string;
  outputPath: string;
  typeName: string;
}

const SCHEMAS: SchemaConfig[] = [
  {
    schemaPath: 'rum-events-format/schemas/rum-events-browser-schema.json',
    outputPath: 'src/domain/rum/rumEvent.types.ts',
    typeName: 'RumEvent',
  },
  {
    schemaPath: 'rum-events-format/schemas/telemetry-events-schema.json',
    outputPath: 'src/domain/telemetry/telemetryEvent.types.ts',
    typeName: 'TelemetryEvent',
  },
];

async function generateTypesForSchema(config: SchemaConfig) {
  printLog(`Reading schema from: ${config.schemaPath}`);

  // Read the JSON schema
  const schemaContent = fs.readFileSync(config.schemaPath, 'utf-8');
  const schema = JSON.parse(schemaContent);

  printLog(`Generating TypeScript types for ${config.typeName}...`);

  // Generate TypeScript types
  const ts = await compile(schema, config.typeName, {
    cwd: path.dirname(config.schemaPath), // Set working directory for resolving $ref
    bannerComment: `/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file is automatically generated from rum-events-format JSON schemas.
 * Source: ${config.schemaPath}
 *
 * To update these types:
 *   yarn json-schemas:sync    # Update submodule and regenerate
 *   yarn json-schemas:generate # Regenerate from current submodule
 */`,
    style: {
      semi: true,
      singleQuote: true,
      trailingComma: 'es5',
      printWidth: 100,
    },
  });

  // Write to output file
  printLog(`Writing types to: ${config.outputPath}`);
  fs.writeFileSync(config.outputPath, ts);

  // Format the generated file with prettier to match project formatting rules
  printLog('Formatting with prettier...');
  execSync(`prettier --write ${config.outputPath}`, { stdio: 'inherit' });
}

async function generateTypes() {
  for (const config of SCHEMAS) {
    await generateTypesForSchema(config);
  }
  printLog('✓ Type generation complete!');
}

generateTypes().catch((error) => {
  console.error('Error generating types:', error);
  process.exit(1);
});
