import type { compile as CompileFn } from 'json-schema-to-typescript';
import { execSync } from 'node:child_process';
import * as fs from 'node:fs';
import * as path from 'node:path';
import { printLog } from './lib/executionUtils.ts';

// needed because using a fork instead of the npm package
// TODO remove when json-schema-to-typescript natively supports readOnly
const JSON2TYPE_PATH = path.join(import.meta.dirname, '../node_modules/json-schema-to-typescript');

let jsonSchemaToTypescriptCache: Promise<typeof CompileFn> | undefined;

function getCompile(): Promise<typeof CompileFn> {
  if (!jsonSchemaToTypescriptCache) {
    jsonSchemaToTypescriptCache = import('json-schema-to-typescript')
      .catch((error: NodeJS.ErrnoException) => {
        if (error.code !== 'ERR_MODULE_NOT_FOUND') throw error;
        buildJsonSchemaToTypescript();
        return import('json-schema-to-typescript');
      })
      .then((mod) => mod.compile);
  }
  return jsonSchemaToTypescriptCache;
}

function buildJsonSchemaToTypescript() {
  printLog('Building json-schema-to-typescript...');
  // due to installation in node_modules, some of these steps can fail;
  // the built version still behaves correctly though
  // With yarn 3+, the 'test/' folder is not present, so all built files are put directly in the
  // 'dist/' folder instead of 'dist/src/'. Using an explicit '--rootDir' fixes this issue.
  try {
    execSync('npm i', { cwd: JSON2TYPE_PATH, stdio: 'inherit' });
  } catch {
    // ignore
  }
  try {
    execSync('npm run clean', { cwd: JSON2TYPE_PATH, stdio: 'inherit' });
  } catch {
    // ignore
  }
  try {
    execSync('npm exec -- tsc --declaration --rootDir .', { cwd: JSON2TYPE_PATH, stdio: 'inherit' });
  } catch {
    // ignore
  }
}

interface SchemaConfig {
  schemaPath: string;
  outputPath: string;
  typeName: string;
}

const SCHEMAS: SchemaConfig[] = [
  {
    schemaPath: 'rum-events-format/schemas/rum-events-browser-schema.json',
    outputPath: 'src/domain/rum/rumEvent.types.ts',
    typeName: 'RumEvent',
  },
  {
    schemaPath: 'rum-events-format/schemas/telemetry-events-schema.json',
    outputPath: 'src/domain/telemetry/telemetryEvent.types.ts',
    typeName: 'TelemetryEvent',
  },
  {
    schemaPath: 'rum-events-format/schemas/profiling-browser-schema.json',
    outputPath: 'src/domain/profiling/profilingEvent.types.ts',
    typeName: 'BrowserProfiling',
  },
];

async function generateTypesForSchema(config: SchemaConfig) {
  printLog(`Reading schema from: ${config.schemaPath}`);

  const schemaContent = fs.readFileSync(config.schemaPath, 'utf-8');
  const schema = JSON.parse(schemaContent);

  printLog(`Generating TypeScript types for ${config.typeName}...`);

  const compile = await getCompile();
  const ts = await compile(schema, config.typeName, {
    cwd: path.dirname(config.schemaPath), // Set working directory for resolving $ref
    bannerComment: `/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file is automatically generated from rum-events-format JSON schemas.
 * Source: ${config.schemaPath}
 *
 * To update these types:
 *   yarn json-schemas:sync    # Update submodule and regenerate
 *   yarn json-schemas:generate # Regenerate from current submodule
 */`,
    style: {
      semi: true,
      singleQuote: true,
      trailingComma: 'es5',
      printWidth: 100,
    },
  });

  printLog(`Writing types to: ${config.outputPath}`);
  fs.writeFileSync(config.outputPath, ts);

  printLog('Formatting with prettier...');
  execSync(`prettier --write ${config.outputPath}`, { stdio: 'inherit' });
}

async function generateTypes() {
  for (const config of SCHEMAS) {
    await generateTypesForSchema(config);
  }
  printLog('✓ Type generation complete!');
}

generateTypes().catch((error) => {
  console.error('Error generating types:', error);
  process.exit(1);
});
