import { compile } from 'json-schema-to-typescript';
import { execSync } from 'node:child_process';
import * as fs from 'node:fs';
import * as path from 'node:path';

const SCHEMA_PATH = 'rum-events-format/schemas/rum-events-browser-schema.json';
const OUTPUT_PATH = 'src/rumEvent.types.ts';

async function generateTypes() {
  console.log('Reading schema from:', SCHEMA_PATH);

  // Read the JSON schema
  const schemaContent = fs.readFileSync(SCHEMA_PATH, 'utf-8');
  const schema = JSON.parse(schemaContent);

  console.log('Generating TypeScript types...');

  // Generate TypeScript types
  const ts = await compile(schema, 'RumEvent', {
    cwd: path.dirname(SCHEMA_PATH), // Set working directory for resolving $ref
    bannerComment: `/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 *
 * This file is automatically generated from rum-events-format JSON schemas.
 * Source: ${SCHEMA_PATH}
 *
 * To update these types:
 *   yarn json-schemas:sync    # Update submodule and regenerate
 *   yarn json-schemas:generate # Regenerate from current submodule
 */`,
    style: {
      semi: true,
      singleQuote: true,
      trailingComma: 'es5',
      printWidth: 100,
    },
  });

  // Write to output file
  console.log('Writing types to:', OUTPUT_PATH);
  fs.writeFileSync(OUTPUT_PATH, ts);

  // Format the generated file with prettier to match project formatting rules
  console.log('Formatting with prettier...');
  execSync(`prettier --write ${OUTPUT_PATH}`, { stdio: 'inherit' });

  console.log('✓ Type generation complete!');
}

generateTypes().catch((error) => {
  console.error('Error generating types:', error);
  process.exit(1);
});
